# Principal Component Analysis

### Build a model that predicts the car weight on basis of different properties of the car including car's manufacturer and model details

In [1]:
path = r"https://raw.githubusercontent.com/samrudhi-shirode/Datasets/refs/heads/main/Cars93.csv"
import pandas as pd 
df = pd.read_csv(path,na_values=['NA',''],keep_default_na=False)
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

# Perform basic data quality checks

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     str
 2   Model               93 non-null     str
 3   Type                93 non-null     str
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             89 non-null     str
 10  DriveTrain          93 non-null     str
 11  Cylinders           93 non-null     str
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     str
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     str
 27  Make                93 non-null     str
dtypes: float64(7), int64(12), str(9)
memory usage: 20.5 KB

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df = df.drop_duplicates()

In [5]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

# Data Cleaning and Data Scaling

In [6]:
import os
os.chdir(r"C:\Users\SAMRUDHI\OneDrive\Desktop\DATA SCIENCE\Machine Learning\repository")

In [7]:
df.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='str')

# Separate X and Y features

In [8]:
X = df.drop(columns='Weight')
Y = df[['Weight']]

In [9]:
from Data_Cleaning_and_Preprocessing.Data_Cl_Pre import data_preparation_cat_con

In [10]:
X_pre = data_preparation_cat_con(X)
X_pre.head()

,cat__Manufacturer_Acura,cat__Manufacturer_Audi,cat__Manufacturer_BMW,cat__Manufacturer_Buick,cat__Manufacturer_Cadillac,cat__Manufacturer_Chevrolet,cat__Manufacturer_Chrylser,cat__Manufacturer_Chrysler,cat__Manufacturer_Dodge,cat__Manufacturer_Eagle,...,con__RPM,con__Rev.per.mile,con__Fuel.tank.capacity,con__Passengers,con__Length,con__Wheelbase,con__Width,con__Turn.circle,con__Rear.seat.room,con__Luggage.room
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.717489,1.129530,-1.062184,-0.083243,-0.427186,-0.286932,-0.366184,-0.610436,-0.449727,-1.037572
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.369586,0.005661,0.409445,-0.083243,0.812171,1.629649,0.431983,-0.298510,0.740403,0.391972
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.369586,-0.105713,0.072197,-0.083243,-0.220626,-0.286932,-0.632239,-0.610436,0.060329,0.034586
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.369586,0.410659,1.359872,0.884457,0.674465,0.302785,0.165927,-0.610436,1.080441,1.106743
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.706562,0.430909,1.359872,-1.050944,0.192493,0.745073,-0.100128,0.013416,-0.279708,-0.322800

# Separate training and testing features

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X_pre,Y,train_size=0.75,random_state=21)

# Create the principal components using PCA

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X_pre)

PCA(n_components=2)

In [13]:
X_pca = pca.transform(X_pre)
X_pca

array([[-2.47922078,  0.62357303],
       [ 2.86389802,  1.94328955],
       [ 0.7200461 ,  1.80942091],
       [ 2.75190227,  2.01139528],
       [ 1.34756221,  2.53845552],
       [ 0.19252064, -1.55810249],
       [ 3.52400481, -1.67759992],
       [ 6.68332508, -2.2907676 ],
       [ 3.01182206,  0.0493757 ],
       [ 5.8768794 , -0.68515706],
       [ 5.31823701,  2.7322808 ],
       [-2.01984612, -0.93954465],
       [-1.57139123, -1.23690103],
       [ 1.13908334, -0.60827948],
       [ 0.58415428, -1.77175692],
       [ 3.09912868, -2.24693131],
       [ 5.07003113, -3.20317491],
       [ 5.41278345, -2.46237873],
       [ 3.99264595,  3.76646715],
       [ 2.57705662, -1.49236777],
       [ 0.55555886, -1.50852429],
       [ 3.72664763, -0.98571655],
       [-4.32773513, -0.47799791],
       [-2.13343225, -1.23861443],
       [-0.41542025, -1.79714999],
       [ 2.42050249, -1.32709911],
       [ 0.76676574, -1.99575587],
       [ 1.06701449,  3.19340593],
       [-3.46757569, -0.41950514],
       [ 2.71438627, -0.6417755 ],
       [-5.85282887, -0.80071261],
       [-2.83811013, -0.25262244],
       [-1.36863429, -1.78171849],
       [-1.1150009 , -0.25968753],
       [-1.28404512, -0.29891967],
       [ 3.2186614 , -1.57214892],
       [ 1.50160941, -0.94777769],
       [ 5.26362865, -2.18481568],
       [-7.54746583, -0.29997217],
       [-4.20136228,  0.33449506],
       [-1.9320266 ,  1.871982  ],
       [-4.568217  , -0.18821208],
       [-0.8383309 ,  0.43631354],
       [-4.61569328, -0.61337324],
       [-2.97666138, -0.11226455],
       [-4.59752005,  0.5531719 ],
       [-0.45414318, -0.32872244],
       [ 5.56242217,  4.30681718],
       [ 1.65279076,  1.59798404],
       [ 1.80725636,  4.08762652],
       [ 4.45880226, -0.08388716],
       [ 6.50740105, -0.24426536],
       [-3.89933358, -1.04063131],
       [-3.14437584, -0.49573515],
       [-0.90425002,  0.02362033],
       [ 1.87859259, -0.92844632],
       [ 0.14274116,  4.96328707],
       [-0.47348942,  2.22530336],
       [ 4.10082654,  5.77166352],
       [-4.00581181,  1.36035039],
       [ 2.2751392 , -2.00231602],
       [-3.78974851, -0.217515  ],
       [ 2.052128  ,  1.57268415],
       [-3.81364009,  0.30417424],
       [-0.8485015 ,  0.01564153],
       [ 2.39548935, -1.25608365],
       [ 1.25594988,  0.36572112],
       [-1.08760346, -0.49315954],
       [-0.01640577, -1.07237299],
       [ 3.41948306, -1.81447429],
       [ 3.3687034 , -1.57964433],
       [-2.54581846,  0.10548092],
       [-4.26981945, -0.97943738],
       [-2.19258746, -0.90316006],
       [ 1.20116649, -0.17869131],
       [ 1.76803785, -0.50167861],
       [ 3.21576414, -1.00804626],
       [-0.60147039,  2.28910402],
       [-2.58332286, -1.44405825],
       [-6.78274626,  0.53516672],
       [-3.1991184 , -0.52387378],
       [-1.21525298,  0.73294795],
       [-6.57751368,  0.13355779],
       [-5.1825948 , -0.24296623],
       [-1.87322545,  1.1025804 ],
       [-0.28363506,  0.19271694],
       [ 2.05338474, -0.76154698],
       [-4.72407192,  0.14799924],
       [ 1.68715895, -1.46613934],
       [-1.11993534,  0.71102865],
       [-0.80232219,  2.34327413],
       [-0.29887114,  0.76482963],
       [ 0.63703317,  1.92699125]])

# Create new data using the principal components

In [14]:
X_new = pd.DataFrame(X_pca)
X_new.head()

          0         1
0 -2.479221  0.623573
1  2.863898  1.943290
2  0.720046  1.809421
3  2.751902  2.011395
4  1.347562  2.538456

In [15]:
X_new.columns = ['PC1','PC2']
X_new.head()

        PC1       PC2
0 -2.479221  0.623573
1  2.863898  1.943290
2  0.720046  1.809421
3  2.751902  2.011395
4  1.347562  2.538456

In [16]:
x_newtrain,x_newtest,y_train,y_test = train_test_split(X_new,Y,train_size=0.8,random_state=21)

# Model Building

In [17]:
from sklearn.ensemble import RandomForestRegressor
rn = RandomForestRegressor(n_estimators=50,max_depth=5)
rn.fit(x_newtrain,y_train)

c:\Users\SAMRUDHI\OneDrive\Desktop\DATA SCIENCE\Machine Learning\repository\venv\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=5, n_estimators=50)

In [18]:
rn.score(x_newtrain,y_train)

0.9819074262588079

In [19]:
rn.score(x_newtest,y_test)

0.8946151821066812